dist: bionic

language: python
python:
  - 3.6

# command to install dependencies
install:
  - "pip install flake8"
  - "pip install black"
  - "pip install -r requirements.txt"

# check code formating
before_script:
  - flake8
  - black --diff --check ./

# command to run tests
script:
  - pytest
